# Generated by Django 3.1.7 on 2021-04-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_code', models.IntegerField()),
                ('Name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('medicine_picture', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'medicines',
            },
        ),
    ]
